### ISSUE TITLE
This is too cool for the internet

### ISSUE THREAD

**Issue by duereg** [fpvwiki/wiki#1]
Could you find another place to put this information? Someplace cooler?

**Comment by alexgorbatchev** [comment]
It's here... http://fpv.wiki

How did you find this anyway? :)

**Comment by duereg** [comment]
I stalk you on the regular. 

I was looking at your github profile, and I was curious why you had like 200 commits in the last three days.

**Comment by alexgorbatchev** [comment]
Oh, that's clever :) I guess forward.js isn't keeping your attention?

**Comment by duereg** [comment]
I only have eyes for your commits, Alex
